# Generated by Django 5.0.3 on 2024-04-20 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_logradouro', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_imoveis',
            },
        ),
    ]
