# Generated by Django 5.0.3 on 2024-04-20 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_tipocontrato'),
        ('registro', '0003_alter_perfil_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_de_inicio', models.DateField()),
                ('data_de_fim', models.DateField()),
                ('esta_ativo', models.BooleanField(default=True)),
                ('valor_total', models.FloatField()),
                ('valor_parcela', models.FloatField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.imovel')),
                ('locatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.perfil')),
                ('tipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tipocontrato')),
            ],
            options={
                'db_table': 'tb_contratos',
            },
        ),
    ]
