# Generated by Django 5.0.3 on 2024-04-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoAluguelTipoContratoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('observacoes', models.TextField()),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.imovel')),
                ('tipo_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tipocontrato')),
            ],
            options={
                'db_table': 'informacoes_aluguel_tipo_contrato_imovel',
            },
        ),
    ]
