# Generated by Django 5.0.3 on 2024-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_informacaoalugueltipocontratoimovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaoalugueltipocontratoimovel',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
