# Generated by Django 5.0.3 on 2024-04-27 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_informacaoalugueltipocontratoimovel_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_parcela', models.IntegerField()),
                ('valor_parcela', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.contrato')),
            ],
            options={
                'db_table': 'tb_parcelamentos',
            },
        ),
    ]
