"""empty message

Revision ID: aacc19722760
Revises: 43701fd5b7fe
Create Date: 2024-02-10 18:17:42.566469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacc19722760'
down_revision: Union[str, None] = '43701fd5b7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_controle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('total_horas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servico_id'], ['tb_servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_controle')
    # ### end Alembic commands ###
