"""migracao inicial

Revision ID: d6c30dc863d0
Revises: 
Create Date: 2024-02-10 16:46:24.999137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c30dc863d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_dicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_postagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_postagens_categorias',
    sa.Column('postagem_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['tb_categorias.id'], ),
    sa.ForeignKeyConstraint(['postagem_id'], ['tb_postagens.id'], ),
    sa.PrimaryKeyConstraint('postagem_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_postagens_categorias')
    op.drop_table('tb_postagens')
    op.drop_table('tb_perfis')
    op.drop_table('tb_usuarios')
    op.drop_table('tb_dicas')
    op.drop_table('tb_categorias')
    # ### end Alembic commands ###
