"""empty message

Revision ID: f8d6744df2c8
Revises: d6c30dc863d0
Create Date: 2024-02-10 16:55:23.391751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d6744df2c8'
down_revision: Union[str, None] = 'd6c30dc863d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_usuarios', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tb_usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_usuarios', 'atualizado_em')
    op.drop_column('tb_usuarios', 'criado_em')
    # ### end Alembic commands ###
