# Generated by Django 5.0.3 on 2024-04-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=1)),
                ('data_de_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'tb_perfis',
            },
        ),
    ]
