# Generated by Django 5.0.3 on 2024-04-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_perfil_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('perfil_bloqueado', 'Usuário com perfil bloqueado não pode acessar a própria página de perfil'),)},
        ),
    ]
